/*
 * CARIMBO postmark mark — geometry generated by tools/carimbo-geometry.mjs
 * (DESIGN.md §6: computed, never eyeballed). Do not hand-edit path data;
 * re-run the generator and paste. Prints in currentColor; per DESIGN.md §6
 * the mark is set only in ink or stamp violet and is never rotated.
 */

import { useId } from "react";

const TOP_ARC = "M 15.5 60 A 44.5 44.5 0 1 1 104.5 60";
const BOT_ARC = "M 7.22 60 A 52.78 52.78 0 1 0 112.78 60";

const WAVES = [
  "M 131 48.5 Q 136.252 43.9 139.25 43.9 Q 142.248 43.9 147.5 48.5 Q 152.752 53.1 155.75 53.1 Q 158.748 53.1 164 48.5 Q 169.252 43.9 172.25 43.9 Q 175.248 43.9 180.5 48.5 Q 185.752 53.1 188.75 53.1 Q 191.748 53.1 197 48.5 Q 202.252 43.9 205.25 43.9 Q 208.248 43.9 213.5 48.5 Q 218.752 53.1 221.75 53.1 Q 224.748 53.1 230 48.5 Q 235.252 43.9 238.25 43.9 Q 241.248 43.9 246.5 48.5 Q 251.752 53.1 254.75 53.1 Q 257.748 53.1 263 48.5",
  "M 131 60 Q 136.252 55.4 139.25 55.4 Q 142.248 55.4 147.5 60 Q 152.752 64.6 155.75 64.6 Q 158.748 64.6 164 60 Q 169.252 55.4 172.25 55.4 Q 175.248 55.4 180.5 60 Q 185.752 64.6 188.75 64.6 Q 191.748 64.6 197 60 Q 202.252 55.4 205.25 55.4 Q 208.248 55.4 213.5 60 Q 218.752 64.6 221.75 64.6 Q 224.748 64.6 230 60 Q 235.252 55.4 238.25 55.4 Q 241.248 55.4 246.5 60 Q 251.752 64.6 254.75 64.6 Q 257.748 64.6 263 60",
  "M 131 71.5 Q 136.252 66.9 139.25 66.9 Q 142.248 66.9 147.5 71.5 Q 152.752 76.1 155.75 76.1 Q 158.748 76.1 164 71.5 Q 169.252 66.9 172.25 66.9 Q 175.248 66.9 180.5 71.5 Q 185.752 76.1 188.75 76.1 Q 191.748 76.1 197 71.5 Q 202.252 66.9 205.25 66.9 Q 208.248 66.9 213.5 71.5 Q 218.752 76.1 221.75 76.1 Q 224.748 76.1 230 71.5 Q 235.252 66.9 238.25 66.9 Q 241.248 66.9 246.5 71.5 Q 251.752 76.1 254.75 76.1 Q 257.748 76.1 263 71.5",
];

const MINI_WAVES = [
  "M 11 52 Q 15.775 47.8 18.5 47.8 Q 21.225 47.8 26 52 Q 30.775 56.2 33.5 56.2 Q 36.225 56.2 41 52 Q 45.775 47.8 48.5 47.8 Q 51.225 47.8 56 52 Q 60.775 56.2 63.5 56.2 Q 66.225 56.2 71 52 Q 75.775 47.8 78.5 47.8 Q 81.225 47.8 86 52 Q 90.775 56.2 93.5 56.2 Q 96.225 56.2 101 52 Q 105.775 47.8 108.5 47.8",
  "M 11 68 Q 15.775 63.8 18.5 63.8 Q 21.225 63.8 26 68 Q 30.775 72.2 33.5 72.2 Q 36.225 72.2 41 68 Q 45.775 63.8 48.5 63.8 Q 51.225 63.8 56 68 Q 60.775 72.2 63.5 72.2 Q 66.225 72.2 71 68 Q 75.775 63.8 78.5 63.8 Q 81.225 63.8 86 68 Q 90.775 72.2 93.5 72.2 Q 96.225 72.2 101 68 Q 105.775 63.8 108.5 63.8",
];

export function Postmark({
  withWaves = true,
  date,
  className,
  label = "MailToBills postmark",
}: {
  withWaves?: boolean;
  date?: string;
  className?: string;
  label?: string;
}) {
  const width = withWaves ? 276 : 120;
  return (
    <svg
      viewBox={`0 0 ${width} 120`}
      className={className}
      role="img"
      aria-label={label}
    >
      <defs>
        <path id="pm-top" d={TOP_ARC} />
        <path id="pm-bot" d={BOT_ARC} />
      </defs>
      <circle
        cx="60"
        cy="60"
        r="57"
        fill="none"
        stroke="currentColor"
        strokeWidth="2.5"
      />
      <circle
        cx="60"
        cy="60"
        r="40"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.25"
      />
      <text
        fontSize="12.5"
        letterSpacing="0.28em"
        fill="currentColor"
        className="font-display font-semibold"
      >
        <textPath href="#pm-top" startOffset="50%" textAnchor="middle">
          MAILTOBILLS
        </textPath>
      </text>
      <text
        fontSize="8.5"
        letterSpacing="0.34em"
        fill="currentColor"
        className="font-display font-semibold"
      >
        <textPath href="#pm-bot" startOffset="50%" textAnchor="middle">
          VIA POSTAL
        </textPath>
      </text>
      {date ? (
        <text
          x="60"
          y="64"
          textAnchor="middle"
          fontSize="12"
          fill="currentColor"
          className="font-mono font-bold"
        >
          {date}
        </text>
      ) : (
        <g stroke="currentColor" strokeWidth="1.25">
          <line x1="38" y1="55" x2="82" y2="55" />
          <line x1="38" y1="65" x2="82" y2="65" />
        </g>
      )}
      {withWaves && (
        <g
          fill="none"
          stroke="currentColor"
          strokeWidth="2.5"
          strokeLinecap="round"
        >
          {WAVES.map((d) => (
            <path key={d.slice(0, 12)} d={d} />
          ))}
        </g>
      )}
    </svg>
  );
}

/** Small cancellation mark (§6 favicon variant): ring + waves, no text. */
export function PostmarkMini({ className }: { className?: string }) {
  const clipId = useId();
  return (
    <svg viewBox="0 0 120 120" className={className} aria-hidden="true">
      <defs>
        <clipPath id={clipId}>
          <circle cx="60" cy="60" r="49" />
        </clipPath>
      </defs>
      <circle
        cx="60"
        cy="60"
        r="54"
        fill="none"
        stroke="currentColor"
        strokeWidth="7"
      />
      <g
        clipPath={`url(#${clipId})`}
        fill="none"
        stroke="currentColor"
        strokeWidth="6"
        strokeLinecap="round"
      >
        {MINI_WAVES.map((d) => (
          <path key={d.slice(0, 12)} d={d} />
        ))}
      </g>
    </svg>
  );
}
