/*
 * CARIMBO postmark mark — geometry generated by tools/carimbo-geometry.mjs
 * (DESIGN.md §6: computed, never eyeballed). Do not hand-edit path data;
 * re-run the generator and paste.
 */

const TOP_ARC = "M 15.5 60 A 44.5 44.5 0 1 1 104.5 60";
const BOT_ARC = "M 7.22 60 A 52.78 52.78 0 1 0 112.78 60";

const WAVES = [
  "M 131 48.5 Q 136.252 43.9 139.25 43.9 Q 142.248 43.9 147.5 48.5 Q 152.752 53.1 155.75 53.1 Q 158.748 53.1 164 48.5 Q 169.252 43.9 172.25 43.9 Q 175.248 43.9 180.5 48.5 Q 185.752 53.1 188.75 53.1 Q 191.748 53.1 197 48.5 Q 202.252 43.9 205.25 43.9 Q 208.248 43.9 213.5 48.5 Q 218.752 53.1 221.75 53.1 Q 224.748 53.1 230 48.5 Q 235.252 43.9 238.25 43.9 Q 241.248 43.9 246.5 48.5 Q 251.752 53.1 254.75 53.1 Q 257.748 53.1 263 48.5",
  "M 131 60 Q 136.252 55.4 139.25 55.4 Q 142.248 55.4 147.5 60 Q 152.752 64.6 155.75 64.6 Q 158.748 64.6 164 60 Q 169.252 55.4 172.25 55.4 Q 175.248 55.4 180.5 60 Q 185.752 64.6 188.75 64.6 Q 191.748 64.6 197 60 Q 202.252 55.4 205.25 55.4 Q 208.248 55.4 213.5 60 Q 218.752 64.6 221.75 64.6 Q 224.748 64.6 230 60 Q 235.252 55.4 238.25 55.4 Q 241.248 55.4 246.5 60 Q 251.752 64.6 254.75 64.6 Q 257.748 64.6 263 60",
  "M 131 71.5 Q 136.252 66.9 139.25 66.9 Q 142.248 66.9 147.5 71.5 Q 152.752 76.1 155.75 76.1 Q 158.748 76.1 164 71.5 Q 169.252 66.9 172.25 66.9 Q 175.248 66.9 180.5 71.5 Q 185.752 76.1 188.75 76.1 Q 191.748 76.1 197 71.5 Q 202.252 66.9 205.25 66.9 Q 208.248 66.9 213.5 71.5 Q 218.752 76.1 221.75 76.1 Q 224.748 76.1 230 71.5 Q 235.252 66.9 238.25 66.9 Q 241.248 66.9 246.5 71.5 Q 251.752 76.1 254.75 76.1 Q 257.748 76.1 263 71.5",
];

export function Postmark({
  withWaves = true,
  date,
  className,
}: {
  withWaves?: boolean;
  date?: string;
  className?: string;
}) {
  const width = withWaves ? 276 : 120;
  return (
    <svg
      viewBox={`0 0 ${width} 120`}
      width={width}
      height={120}
      className={className}
      role="img"
      aria-label="MailToBills postmark"
    >
      <defs>
        <path id="pm-top" d={TOP_ARC} />
        <path id="pm-bot" d={BOT_ARC} />
      </defs>
      <circle
        cx="60"
        cy="60"
        r="57"
        fill="none"
        stroke="currentColor"
        strokeWidth="2.5"
      />
      <circle
        cx="60"
        cy="60"
        r="40"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.25"
      />
      <text
        fontSize="12.5"
        letterSpacing="0.28em"
        fill="currentColor"
        style={{ fontFamily: "var(--font-archivo)", fontWeight: 600 }}
      >
        <textPath href="#pm-top" startOffset="50%" textAnchor="middle">
          MAILTOBILLS
        </textPath>
      </text>
      <text
        fontSize="8.5"
        letterSpacing="0.34em"
        fill="currentColor"
        style={{ fontFamily: "var(--font-archivo)", fontWeight: 600 }}
      >
        <textPath href="#pm-bot" startOffset="50%" textAnchor="middle">
          VIA POSTAL
        </textPath>
      </text>
      {date ? (
        <text
          x="60"
          y="64"
          textAnchor="middle"
          fontSize="12"
          fill="currentColor"
          style={{ fontFamily: "var(--font-courier)", fontWeight: 700 }}
        >
          {date}
        </text>
      ) : (
        <g stroke="currentColor" strokeWidth="1.25">
          <line x1="38" y1="55" x2="82" y2="55" />
          <line x1="38" y1="65" x2="82" y2="65" />
        </g>
      )}
      {withWaves && (
        <g
          fill="none"
          stroke="currentColor"
          strokeWidth="2.5"
          strokeLinecap="round"
        >
          {WAVES.map((d) => (
            <path key={d.slice(0, 12)} d={d} />
          ))}
        </g>
      )}
    </svg>
  );
}
